global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - '/etc/prometheus/alert_rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
        labels:
          instance_name: 'DevOps-02'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance_name: 'DevOps-02'
      - targets: ['10.10.0.151:9100']
        labels:
          instance_name: 'DevOps-01'
      - targets: ['10.10.0.34:9101']
        labels:
          instance_name: 'AWS-01'
      - targets: ['10.10.0.214:9100'] 
        labels:
          instance_name: 'Jenkins-01'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          instance_name: 'DevOps-02'
      - targets: ['10.10.0.34:8081']
        labels:
          instance_name: 'AWS-01'
      - targets: ['10.10.0.214:8081'] 
        labels:
          instance_name: 'Jenkins-01'

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
        labels:
          instance_name: 'DevOps-02'

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
        labels:
          instance_name: 'DevOps-02'

  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']
        labels:
          instance_name: 'DevOps-02'
      - targets: ['10.10.0.214:9080'] 
        labels:
          instance_name: 'Jenkins-01'
      - targets: ['10.10.0.34:9080']
        labels:
          instance_name: 'AWS-01'
      - targets: ['10.10.0.151:9080']
        labels:
          instance_name: 'DevOps-01'
