global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100', '${REMOTE_NODE_IP_1}:9100', '${REMOTE_NODE_IP_2}:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080', '${REMOTE_NODE_IP_1}:8080', '${REMOTE_NODE_IP_2}:8080']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
