apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: ${PROMETHEUS_URL}
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: ${LOCAL_LOKI_URL}
    isDefault: false
    editable: true

  - name: Remote Loki
    type: loki
    access: proxy
    url: ${REMOTE_LOKI_URL}
    isDefault: false
    editable: true
