server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system-logs
    static_configs:
      - targets: ['localhost']
        labels:
          job: varlogs
          host: DevOps-02
          __path__: /var/log/*log

  - job_name: container-logs-docker
    static_configs:
      - targets: ['localhost']
        labels:
          job: containerlogs
          host: DevOps-02
          __path__: /var/lib/docker/containers/*/*.log

  - job_name: container-logs-podman
    static_configs:
      - targets: ['localhost']
        labels:
          job: containerlogs
          host: DevOps-02
          __path__: /var/lib/containers/storage/overlay-containers/*/userdata/ctr.log
